ci: sanitize artifact names
hello-nrfcloud/firmware pull request #356
Opened 2024-09-25 14:32 UTC by maxd-nordic

Make the artifact names more obivous.
Also, for nRF5340 builds, separate HEX files for
APP core and NET core are released so nrfutil-device can be used.

2024-09-25 14:35 UTC, coderbyheart requested changes
hello-nrfcloud identifier is a duplication, because filename already includes hello.nrfcloud.com

2024-09-25 14:41 UTC, maxd-nordic commented
> hello-nrfcloud identifier is a duplication, because filename already includes hello.nrfcloud.com

should we then have names like this?

connectivity_bridge-${{ env.VERSION }}-thingy91x-nrf53-merged.hex
hello.nrfcloud.com-${{ env.VERSION }}-thingy91x-nrf91.hex

2024-09-25 15:00 UTC, coderbyheart commented
That looks good.

2024-09-25 15:01 UTC, coderbyheart reviewed
This RegEx needs fixing, too, if you change the file names:
https://github.com/hello-nrfcloud/firmware/blob/6e55eac58e01c8fea9832482ff11a31fce97c2f7/.github/workflows/register-firmware-bundles.mjs#L13

2024-09-27 08:54 UTC, coderbyheart approved these changes

2024-09-27 11:18 UTC, merged